# Generated by Django 6.1.1 on 2026-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster_url', models.URLField()),
                ('backdrop_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('release_year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
